name: Audit template lockfiles
on:
  pull_request:
    branches:
      - master

jobs:
  audit:
    name: Audit template lockfiles
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.5.1
