permissions: write-all # Equivalent to default permissions plus id-token: write
env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: false
name: Build template metadata
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Check out branch
        uses: actions/checkout@v3
        with:
          token: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}

      - name: Build metadata
        run: |
          make metadata

      - name: Publish metadata.json file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: metadata/dist/metadata.json
          commit_message: Update metadata.json
